# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.8.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_version: 13.0
org_name: CreuBlanca
org_slug: tegin
rebel_module_groups: []
repo_description: Queue management
repo_name: Queue managament
repo_slug: kiwi
repo_website: https://github.com/tegin/kiwi
travis_apt_packages: []
travis_apt_sources: []

